config/routes.rb
Rails.application.routes.draw do
  devise_for :companies
  resources :departments do
    resources :employees
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'departments#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :departaments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         

end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :company
  has_many :employees, dependent: :destroy
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :department
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_company!
  
  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.where company_id: current_company.id
    @user_id = current_company.id    
    if params.key?("id")
      @department= @departments.find(params["id"])
    else
      @department = Department.new(company: Company.find(@user_id))
    end
  end
  
  # GET /departments/1
  # GET /departments/1.json
  def show
    
  end
  
  # GET /departments/new
  def new
    @user_id = current_company.id
    @department = Department.new
  end
  
  # GET /departments/1/edit
  def edit
    @user_id = current_company.id 
  end
  
  # POST /departments
  # POST /departments.json
  def create
    @user_id = current_company.id
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to departments_url, notice: 'El departamento fue creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    puts "ESTOO ES LOQ UE ENCESITOOOOO #{@user_id}"       
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to departments_path, notice: 'El departamento fue guardado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'El departamento fue borrado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def department_params
      params.require(:department).permit(:name, :company_id)
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all.where(department_id: params[:department_id])

    @department = Department.find params[:department_id]

    if params.key?("id-emp")
      @employee= @employees.find(params["id-emp"])
    else
      @employee = Employee.new(department: @department)
    end
  end
      

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    
    @employee = Employee.new(employee_params)
    respond_to do |format|
      if @employee.save
        format.html { redirect_to department_employees_path, notice: 'El empeado fue creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to department_employees_url, notice: 'El empleado fue guardado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    # @employee = Employee.find params[:id]
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to department_employees_url, notice: 'El empleado fue borrado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :last_name, :dni, :phone_number, :email, :bank, :account_type, :account_number, :phone_number_2, :phone_emergency, :department_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  

end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/departments/_form.html.erb
<%= form_with(model: department, local: true) do |form| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
      <% department.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :nombre_del_departamento %>
    <%= form.text_field :name, id: :department_name, class: "form-control", value:"#{department.name}" %>
  </div>
  
  <%= form.number_field :company_id, id: :department_company_id, value: @user_id, hidden: true %>  

  <div class="actions">
    <%= form.submit value: "Guardar", class:"col btn btn-primary"%>
  </div>
<% end %>

app/views/departments/index.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success alert-dismissible text-center fade show"><%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </p>
<% end %>

<div class="row">
  <div class= "col-7"> 
    <div class="row">
      <h1 class= "col-12">Departamentos</h1>
    </div>
  
    <% if @departments.length != 0 %>    
      <table class="table table-striped">
        <thead>
          <tr>
            <th >Nombre del departamento</th>
            <th >Cantidad de empleados</th>      
            <th class= "text-center">Acciones</th>
          </tr>
        </thead>

        <tbody>
          <% @departments.each do |department| %>
            <tr> 
              <td><%= link_to  department.name, department_employees_path(department) %></td>
              <td class= "text-center"><%= department.employees.length %></td>
              <td >
                <%= link_to  department_employees_path(department), class:"btn btn-primary" do %>              
                  <i class="fas fa-users"></i>
                <% end %>                
                <%= link_to departments_path + "/?id=#{department.id}", class:"btn btn-outline-primary" do %>
                  <i class="fas fa-pencil-alt "></i>
                <% end %>
                <%= link_to (fa_icon "trash-alt"), department, method: :delete, data: { confirm: 'Estas a punto de borrar un departamento y por consecuencia todos sus trabajdores, ¿Estas seguro?' }, class:"btn btn-outline-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class = "row"> 

        <div class = "d-flex col justify-content-center"> 
          <%= image_tag("employees.jpg") %> 
        </div> 
            
      </div> 
        
      <div class = "row"> 
          <h4 class = "col text-center"> Aún no hay departamentos </h4>
      </div>

      <div class = "row"> 
        <h6 class = "col text-center"> Puedes crear tu primer departamento utilizadno el siguietne formulario. </h6>
      </div>

    <% end %>
  </div>
  
  <div class= "col-5"> 

    <% if params.key?("id") %>    
      <div class = "row"> 
        <div class = "col">       
          <h1>Modificar departamento</h1>
        </div>
      </div>

      <div class = "row">      
        <div class = "col">              
          <%= render 'form', department: @department, user_id: @user_id %> 
        </div>              
      </div>  

    <% else %>
      <div class = "row"> 
        <div class = "col">       
          <h2>Nuevo departamento</h2>
        </div>
      </div>

      <div class = "row">      
        <div class = "col">              
          <%= render 'form', department: @department, user_id: @user_id %> 
        </div>             
      </div>
    <% end %>
  </div>  

</div>

<%= link_to 'Log out', destroy_company_session_path, method: :delete %> |

app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form', department: @department, user_id: @user_id %>

<%= link_to 'Back', departments_path %>

app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @department.name %>
</p>

<%= link_to 'Edit', edit_department_path(@department) %> |
<%= link_to 'Back', departments_path %>

app/views/employees/_form.html.erb
<%= form_with(model:[@department, @employee], local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "form-row">
    <div class="field form-group col-6">
      <%= form.label :name do%> 
        <strong>Primer nombre*</strong>
      <% end %>
      <%= form.text_field :name, id: :employee_name, class: "form-control", value:"#{employee.name}" %>
    </div>

    <div class="field form-group col-6">
      <%= form.label :last_name do%> 
        <strong>Apellido*</strong>
      <% end %>
      <%= form.text_field :last_name, id: :employee_last_name, class: "form-control", value:"#{employee.last_name}" %>
    </div>
  </div>

  <div class = "form-row">
    <div class="field form-group col-6">
      <%= form.label :dni do%> 
        <strong>Cédula*</strong>
      <% end %>
      <%= form.text_field :dni, id: :employee_dni, class: "form-control", value:"#{employee.dni}" %>
    </div>

    <div class="field form-group col-6  ">
      <%= form.label :phone_number do%> 
        <strong>Celular*</strong>
      <% end %>
      <%= form.text_field :phone_number, id: :employee_phone_number, class: "form-control", value:"#{employee.phone_number}" %>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :correo_electrónico %>
    <%= form.text_field :email, id: :employee_email, class: "form-control", value:"#{employee.email}" %>
  </div>

  <div class = "form-row">
    <div class="field form-group col-6">
      <%= form.label :banco %>
      <%= form.text_field :bank, id: :employee_bank, class: "form-control", value:"#{employee.bank}" %>
    </div>

    <div class="field form-group col-6">
    <%= form.label :tipo_de_cuenta %>
      <%= form.text_field :account_type, id: :employee_account_type, class: "form-control", value:"#{employee.account_type}" %>
    </div>
  </div>

  <div class="field form-group">
    <%= form.label :nro_de_cuenta %>
    <%= form.text_field :account_number, id: :employee_account_number, class: "form-control", value:"#{employee.account_number}" %>
  </div>

  <div class = "form-row">
    <div class="field form-group col-6">
      <%= form.label :telefono_fijo %>
      <%= form.text_field :phone_number_2, id: :employee_phone_number_2, class: "form-control", value:"#{employee.phone_number_2}" %>
    </div>

    <div class="field form-group col-6">
      <%= form.label :telefono_de_emergencia %>
      <%= form.text_field :phone_emergency, id: :employee_phone_emergency, class: "form-control", value:"#{employee.phone_emergency}" %>
    </div>
  </div>

  <%= form.text_field :department_id ,value: params["department_id"],id: :employee_department_id, hidden: true %>

  <div class="actions">
    <%= form.submit value: "Guardar", class:"col btn btn-primary"%>
  </div>
<% end %>

app/views/employees/index.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success alert-dismissible text-center fade show"><%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </p>
<% end %>

<div class = "row">
  <div class = "col-7">
    <div class = "row">
      <%= link_to '<', departments_path, class:"col-1"%>
      <h2 class= "col-11">Empleados de <span id="title"> <%=Department.find(params[:department_id]).name%> </span> </h2>
    </div>

    <% if @employees.length != 0 %>
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Cédula</th>
            <th>Nombre</th>
            <th>Celular</th>
            <th>Acciones</th>
          </tr>
        </thead>

        <tbody>
          <% @employees.each do |employee| %>
            <tr>
              <td><%= employee.dni %></td>  
              <td><%= employee.name %></td>
              <td><%= employee.phone_number %></td>
              
              <td>
                <%= link_to (fa_icon "pencil-alt"), department_employees_path + "/?id-emp=#{employee.id}", class:"btn btn-outline-primary"%>
                <%= link_to (fa_icon "trash-alt"), department_employee_path(id: employee.id), method: :delete, data: { confirm: 'Estas a punto de borrar un empleado, ¿Estas seguro?' }, class:"btn btn-outline-danger" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <div class = "row"> 

        <div class = "d-flex col justify-content-center"> 
          <%= image_tag("employees.jpg") %> 
        </div> 
            
        
      </div> 
      
      <div class = "row"> 
          <h4 class = "col text-center"> Aún no hay empleados </h4>
      </div>

      <div class = "row"> 
        <h6 class = "col text-center"> Puedes crear tu primer empleado utilizadno el siguietne formulario. </h6>
      </div>

    <% end %>
  </div>

  <div class = "col-5">     

    <% if params.key?("id-emp") %>
      <div class = "row"> 
        <div class = "col">       
          <h2>Modificar empleado</h2>
        </div>
      </div>      
      <div class = "row">      
        <div class = "col">              
          <%= render 'form' ,employee: @employee %> 
        </div>             
      </div> 

       
    <% else %>
      <div class = "row"> 
        <div class = "col">       
          <h2>Nuevo empleado</h2>
        </div>
      </div>

      <div class = "row">      
        <div class = "col">              
          <%= render 'form' ,employee: @employee %> 
        </div>             
      </div> 
    <% end %>

    <br>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PROYECTO8Juca</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </head>
  <body>
    <div class="container mx-auto">
     
      <%= yield %>
    </div>
  </body>
</html>

app/views/partials/_header.html.erb
<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <input class="form-control mr-sm-2" type="search" placeholder="Búsqueda de empleados" aria-label="Search">
    <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
  </form>
</nav>